version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.8.0
    steps:
      - checkout
      - run: echo "building NPM module"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-yarn
          command: 'sudo npm install -g yarn'
      - run:
          name: install-all-the-things
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test
      - run:
          name: build
          command: yarn build
#      - run:
#        name: code-coverage
#        command: './node_modules/.bin/nyc report --reporter=text-lcov'
#      - store_artifacts:
#          path: test-results.xml
#          prefix: tests
#      - store_artifacts:
#          path: coverage
#          prefix: coverage
#      - store_test_results:
#          path: test-results.xml