
# @see https://github.com/sbstjn/typescript-npm-boilerplate for some help with this

version: 2

jobs:

  build:

    docker:
      - image: circleci/node:9.7.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "building NPM module"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn test
      - run: yarn build
      - run: npm install dot-json
      - run: $(yarn bin)/dot-json package.json version ${CIRCLE_TAG:1}
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --access=public

#      - run:
#        name: code-coverage
#        command: './node_modules/.bin/nyc report --reporter=text-lcov'
#      - store_artifacts:
#          path: test-results.xml
#          prefix: tests
#      - store_artifacts:
#          path: coverage
#          prefix: coverage
#      - store_test_results:
#          path: test-results.xml
